pull_request_rules:
  - name: merge automated metals update PRs on CI success
    conditions:
      - author=github-actions[bot]
      - title=Update Metals to latest snapshot
      - status-success=Home
    actions:
      merge:
        method: merge
