#! /usr/bin/env bash

# Shows the output of every command
set +x

activate_hm() {
  result/activate
}

rebuild_xmonad_edp() {
  nom build .#homeConfigurations.xmonad-edp.activationPackage
  activate_hm
}

rebuild_xmonad_hdmi() {
  nom build .#homeConfigurations.xmonad-hdmi.activationPackage
  activate_hm
}

rebuild_hyprland_edp() {
  nom build .#homeConfigurations.hyprland-edp.activationPackage
  activate_hm
}

rebuild_hyprland_hdmi() {
  nom build .#homeConfigurations.hyprland-hdmi.activationPackage
  activate_hm
}

rebuild_hyprland_hdmi_mutable() {
  nom build .#homeConfigurations.hyprland-hdmi-mutable.activationPackage
  activate_hm
}

rebuild_niri_hdmi() {
  nom build .#homeConfigurations.niri-hdmi.activationPackage
  activate_hm
}

rebuild_thinkpad() {
  sudo nixos-rebuild switch --flake .#thinkpad-x1
}

rebuild_tongfang() {
  # nix build .#nixosConfigurations.tongfang-amd.config.system.build.toplevel
  # sudo result/bin/switch-to-configuration switch
  sudo nixos-rebuild switch --flake .#tongfang-amd
}

rebuild_tongfang_vm() {
  nixos-rebuild build-vm --flake .#tongfang-amd
}

case $1 in
  "niri")
    rebuild_niri_hdmi;;
  "xmedp")
    rebuild_xmonad_edp;;
  "xmhdmi")
    rebuild_xmonad_hdmi;;
  "hpedp")
    rebuild_hyprland_edp;;
  "hphdmi")
    rebuild_hyprland_hdmi;;
  "hphdmi-mutable")
    rebuild_hyprland_hdmi_mutable;;
  "update-fish")
    fish -c fish_update_completions;;
  "update-nix-index")
    nix-index --filter-prefix '/bin/';;
  "thinkpad")
    rebuild_thinkpad;;
  "tongfang")
    rebuild_tongfang;;
  "vm")
    rebuild_tongfang_vm;;
  *)
    echo "Wrong argument: look at the switch script.";;
esac
