#! /usr/bin/env bash

# Shows the output of every command
set +x

rebuild_home_edp() {
  nix build .#homeConfigurations.gvolpe-edp.activationPackage
  result/activate -b
}

rebuild_home_hdmi() {
  nix build .#homeConfigurations.gvolpe-hdmi.activationPackage
  result/activate -b
}

rebuild_system() {
  # nix build .#nixosConfigurations.tongfang-amd.config.system.build.toplevel
  # sudo result/bin/switch-to-configuration switch
  sudo nixos-rebuild switch --flake .#tongfang-amd
}

restart_X() {
  echo "⚠️ Restarting X11 (requires authentication) ⚠️"
  systemctl restart display-manager
}

case $1 in
  "edp")
    rebuild_home_edp;;
  "hdmi")
    rebuild_home_hdmi;;
  "restart-x")
    restart_X;;
  "update-fish")
    fish -c fish_update_completions;;
  "system")
    rebuild_system;;
  *)
    echo "expected 'edp', 'hdmi', 'restart-x', 'update-fish' or 'system'";;
esac
