# Generated by ‘nixos-generate-config’ and formatted manually
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usb_storage"
        "sd_mod"
        "rtsx_usb_sdmmc"
      ];
      kernelModules = [ ];
    };

    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/7BB3-09C5";
      fsType = "vfat";
    };

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/0fddb262-13c1-46b1-9a5d-216766f47498";
      fsType = "ext4";
    };

  swapDevices = [ ];

}
