name: Nixbuild demo

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v19
      - uses: nixbuild/nixbuild-action@v15
        with:
          nixbuild_ssh_key: ${{ secrets.NIXBUILD_SSH_KEY }}
          generate_summary_for: 'checks'
      - run: nix build .#metals
