name: Garnix status check
description: Determines whether to build the Nix config on GHA or not based on the Garnix status check
inputs:
  github_token:
    required: true
outputs:
  garnix:
    description: "The status check response, which may be failure or success"
    value: ${{ steps.garnix.outputs.status }}
runs:
  using: "composite"
  steps:
    # I got the check suite ID from: https://api.github.com/repos/gvolpe/nix-config/commits/REF/check-runs
    # where REF == branch name (didn't work with the commit sha for some reason)
    - name: Garnix check status
      id: garnix
      shell: bash
      run: |
        STATUS=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.github_token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/gvolpe/nix-config/check-suites/33419075802/check-runs | \
          jq -r '.check_runs | .[] | select (.output.text | contains("monthly CI quota")) | select (.status == "completed") | .conclusion')
        echo "status=$STATUS" | tee -a "$GITHUB_OUTPUT"
