name: Garnix status check
description: Determines whether to build the Nix config on GHA or not based on the Garnix status check
inputs:
  github_token:
    required: true
outputs:
  status:
    description: "The status check response, which may be failure or success"
    value: ${{ steps.garnix.outputs.status }}
runs:
  using: "composite"
  steps:
    - name: Garnix check status
      id: garnix
      shell: bash
      run: |
        # the check suite id can be fetched in different ways for PRs and the main branch
        if [[ ${{ github.ref }} == *"refs/pull"* ]]; then
          COMMIT=${{ github.head_ref }}
        else
          COMMIT=${{ github.ref }}
        fi

        echo "Fetching Suite ID by ref: $COMMIT"

        CHECK_SUITE_ID=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.github_token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/gvolpe/nix-config/commits/$COMMIT/check-runs | \
          jq -r '.check_runs | .[] | select (.name | contains("Evaluate flake.nix")) | .check_suite.id')

        echo "Garnix Check Suite ID: $CHECK_SUITE_ID"

        STATUS=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.github_token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/gvolpe/nix-config/check-suites/$CHECK_SUITE_ID/check-runs | \
          jq -r '.check_runs | .[] | select (.output.text | contains("monthly CI quota")) | select (.status == "completed") | .conclusion')

        echo "status=$STATUS" | tee -a "$GITHUB_OUTPUT"
